[tool.poetry]
name = "job-service"
version = "0.1.0"
description = ""
authors = ["Team Microdata"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.3.2"
Flask-Pydantic = "^0.9.0"
pymongo = "^4.0.2"
pydantic = "^1.9.0"
PyJWT = "^2.4.0"
cryptography = "^41.0.6"
gunicorn = "^20.1.0"
json-logging = "^1.3.0"
tomlkit = "^0.10.1"
pyhumps = "^3.7.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.3.0"
pytest = "^7.1.1"
pytest-dotenv = "^0.5.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
testcontainers = {extras = ["mongodb"], version = "^3.7.0"}
ruff = "^0.1.7"
black = "^23.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79