[tool.poetry]
name = "job-service"
version = "0.1.0"
description = ""
authors = ["Team Microdata"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.1"
Flask-Pydantic = "^0.9.0"
pymongo = "^4.0.2"
pydantic = "^1.9.0"
gunicorn = "^20.1.0"
json-logging = "^1.3.0"
tomlkit = "^0.10.1"
pyhumps = "^3.7.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.1.1"
pytest-dotenv = "^0.5.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
pylint = "^2.14.4"
pycodestyle = "^2.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
